name: Run container-diff

on: 
  workflow_dispatch:

jobs:
  container-diff:
    runs-on: ['ubuntu-latest']
    container:
      image: docker
    name: Run container-diff
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: "${{ secrets.DOCKER_USER }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run container-diff
        uses: GoogleContainerTools/container-diff/actions@master
        with:
          # Note this command is the default and does not need to be included
          command: diff          
          args: registry-1.docker.io/library/python:3.9-bullseye registry-1.docker.io/library/python:3.14-rc-bullseye --type=layer --output=./data.json --json
      - name: View output
        run: cat ./data.json
